In [5]:
import pandas as pd
file = "../analysis/Household_Survey_Analysis.csv"
result = pd.read_csv(file)
result.head()

,House ID,Household Size,Primary Fuel,Fuel mass (KG),Time taken (days),Solid waste/day (Kg),Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,W001,3,LPG,12.5,45,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,W002,4,LPG,12.5,40,1.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,W003,4,LPG,12.5,42,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,W004,1,LPG,3.0,50,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,W005,5,LPG,12.5,30,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
result = result.dropna(axis=1, how='all')
result.head()

,House ID,Household Size,Primary Fuel,Fuel mass (KG),Time taken (days),Solid waste/day (Kg)
0,W001,3,LPG,12.5,45,1.2
1,W002,4,LPG,12.5,40,1.8
2,W003,4,LPG,12.5,42,0.8
3,W004,1,LPG,3.0,50,0.3
4,W005,5,LPG,12.5,30,2.7

In [14]:
!git add .
!git commit -m "Update notebook"
!git push origin main

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../data/Household_Survey_Results.xlsx

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date

In [13]:
result['Daily Fuel Usage (KG/day)'] = result['Fuel mass (KG)'] / result['Time taken (days)']
display(result.head())

,House ID,Household Size,Primary Fuel,Fuel mass (KG),Time taken (days),Solid waste/day (Kg),Daily Fuel Usage (KG/day)
0,W001,3,LPG,12.5,45,1.2,0.277778
1,W002,4,LPG,12.5,40,1.8,0.312500
2,W003,4,LPG,12.5,42,0.8,0.297619
3,W004,1,LPG,3.0,50,0.3,0.060000
4,W005,5,LPG,12.5,30,2.7,0.416667